### PR TITLE
add oas3 optioins which provide openapivalidator options

### PR DESCRIPTION
**Pull request by mstrewe**

### CODE REVIEW

**Comment by lfrestrepog** [comment]
Hi. Any news on this? I'm interested in this feature too. Maybe I could lend a hand or something?

**Comment by mstrewe** [comment]
Oh. Totally forgot that. May I have time next week to fix the conflict

**Comment by mstrewe** [comment]
@HugoMario  can you check again. 

I updated the dode so that you can specifay openapivalidator options so that security is supported.

I updated the example.js so to show the change of the options object

**Comment by mstrewe** [comment]
@lfrestrepog updated. See example.js how to set the optoins.

**Comment by mstrewe** [comment]
@lfrestrepog Does it work for you?

**Comment by lfrestrepog** [comment]
well, yes, I'm waiting for the maintainer of this repo to complete the pull request too 😅
I wonder what else we need to deploy the changes to npm too... it doesn't look like there's much activity here since last June.

**Comment by HugoMario** [comment]
sorry for delay guys, and thanks a lot for adding these PR

**Comment by HugoMario** [comment]
i'll take time later today or on weekend to deploy it to npm

**Comment by HugoMario** [comment]
new version published https://www.npmjs.com/package/oas3-tools

**Pull request merged**
