### PR TITLE
add support pdf in body of request

### PR DESCRIPTION
**Pull request by blowin**
I have a problem, there is no way to send pdf files in the request body. This functionality is very necessary, I don't know how to fix it without updating the library.

Please publish these changes ASAP. Thanks.

### CODE REVIEW

**Comment by blowin** [comment]
for more flexibility you can use 'application/*' instead of 'application/pdf'

**Comment by blowin** [comment]
direct call to 'raw()' without parameters, doesn't work for pdf

**Comment by blowin** [comment]
direct call to 'raw()' without parameters, doesn't work for pdf.

for more flexibility you can use:
1. 'application/*' instead of 'application/pdf'
2. add the ability for users to add any middleware

**Comment by VladislavPetyukevich** [comment]
Same issue

**Comment by HugoMario** [comment]
thanks a lot @blowin for this PR

**Pull request merged**
